### ISSUE TITLE
Error on running coala-quickstart on the coala-quickstart repo itself 

### ISSUE THREAD

**Issue by ishanSrt** [coala/coala-quickstart#219]
Here's the traceback:
```
Traceback (most recent call last):
  File "/Users/ishansrivastava/Desktop/Environments/coala-quickstart_env/bin/coala-quickstart", line 11, in <module>
    load_entry_point('coala-quickstart', 'console_scripts', 'coala-quickstart')()
  File "/Users/ishansrivastava/Desktop/coala-quickstart/coala_quickstart/coala_quickstart.py", line 91, in main
    extracted_information = collect_info(project_dir)
  File "/Users/ishansrivastava/Desktop/coala-quickstart/coala_quickstart/generation/InfoCollector.py", line 17, in collect_info
    [".editorconfig"], project_dir).extract_information()
  File "/Users/ishansrivastava/Desktop/coala-quickstart/coala_quickstart/info_extraction/InfoExtractor.py", line 87, in extract_information
    file_info = self.find_information(fname, pfile)
  File "/Users/ishansrivastava/Desktop/coala-quickstart/coala_quickstart/info_extractors/EditorconfigInfoExtractor.py", line 30, in find_informati$
n
    translate_editorconfig_section_to_regex(section_name))
  File "/Users/ishansrivastava/Desktop/coala-quickstart/coala_quickstart/info_extractors/EditorconfigParsing.py", line 406, in translate_editorcon$
ig_section_to_regex
    self.translate_pattern_to_regex(pat[index:pos],
NameError: name 'self' is not defined
```

Doesn't occur on the coala repo

**Comment by satwikkansal** [comment]
Ah, that's probably due to some `None` object

**Comment by satwikkansal** [comment]
The parser code was taken from https://github.com/editorconfig/editorconfig-core-py , so there aren't many tests here in our repo. Might be worth looking at the repo if this has already been fixed there.

**Comment by ishanSrt** [comment]
@satwikkansal actually I don't understand where you have defined `translate_pattern_to_regex()`. Was it equivalent for 
https://github.com/editorconfig/editorconfig-core-py/blob/d1b3dd3206568b3d6d942ef3c9a9a115dda2383b/editorconfig/fnmatch.py#L114-L220

which is somehow missed?

**Comment by ishanSrt** [comment]
solved by https://github.com/coala/coala-quickstart/pull/225/, don't know why it didn't get clones
