### ISSUE TITLE
failed run coala-quickstart --ci

### ISSUE THREAD

**Issue by Lidilidian** [coala/coala-quickstart#43]
failed to run `coala-quickstart --ci` and got this error :

```
Traceback (most recent call last):

  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 659, in _build_master

    ws.require(__requires__)

  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 967, in require

    needed = self.resolve(parse_requirements(requirements))

  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 858, in resolve

    raise VersionConflict(dist, req).with_context(dependent_req)

pkg_resources.ContextualVersionConflict: (six 1.8.0 (/usr/lib/python3.4/site-packages), Requirement.parse('six>=1.9.0'), {'bandit', 'stevedore'})



During handling of the above exception, another exception occurred:



Traceback (most recent call last):

  File "/usr/bin/coala-quickstart", line 6, in <module>

    from pkg_resources import load_entry_point

  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 3017, in <module>

    @_call_aside

  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 3003, in _call_aside

    f(*args, **kwargs)

  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 3030, in _initialize_master_working_set

    working_set = WorkingSet._build_master()

  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 661, in _build_master

    return cls._build_from_requirements(__requires__)

  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 674, in _build_from_requirements

    dists = ws.resolve(reqs, Environment())

  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 858, in resolve

    raise VersionConflict(dist, req).with_context(dependent_req)

pkg_resources.ContextualVersionConflict: (six 1.8.0 (/usr/lib/python3.4/site-packages), Requirement.parse('six>=1.9.0'), {'bandit', 'stevedore'})
```

**Comment by jayvdb** [comment]
Was this on your own computer?  If yes, which OS & Distribution are you running?

**Comment by sils** [comment]
Hey @Lidilidian we didn't receive a message for quite some time. I believe that your issue will be solved if you install the latest coala-bears release and coala-quickstart release in a fresh virtualenv. This is a typical error for coala development setups since pip isn't particularly strong at getting the right versions for you.

**Comment by Lidilidian** [comment]
okay thanks

2017-02-02 5:25 GMT+07:00 Lasse Schuirmann <notifications@github.com>:

**Comment by sils** [comment]
(that being said if you still experience this with a fresh venv please do reopen it! No intention of closing real bugs here.)
